// Code generated by protoc-gen-gorm_serializer. DO NOT EDIT.
// versions:
// - protoc             v3.21.12
// source: task.proto

package protoc_gen_gorm_serializer_example

import "database/sql/driver"

func (x *TaskStatus) Scan(v any) (err error) {
	*x = TaskStatus(v.(int64))
	return nil
}

func (x TaskStatus) Value() (v driver.Value, err error) {
	return int64(x), nil
}
